# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "my_new_project"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    staging:
      materialized: view #main folder
      jaffle_shop: # folder in dbt
        +database: analytics-380111 # big query project name
        +schema: jaffle_shop # big query dataset name

    stripe: # folder in dbt
      +database: analytics-380111 # big query project name
      +schema: stripe # big query dataset name

    marts: # folder in dbt
      materialized: table
      +database: analytics-380111 # big query project name
      +schema: marts # big query dataset name

    team_one:
      materialized: table
      +database: analytics-380111
      +schema: team_one

    team_two:
      materialized: table
      +database: analytics-380111
      +schema: team_two
